/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/usr/local/lib/node_modules/vuepress/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-5b3139b6",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5b3139b6").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-17bf8350",
    path: "/java/Kafka.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-17bf8350").then(next)
    },
  },
  {
    name: "v-3f7e1856",
    path: "/java/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3f7e1856").then(next)
    },
  },
  {
    path: "/java/index.html",
    redirect: "/java/"
  },
  {
    name: "v-2bf0c1a6",
    path: "/java/Redis.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2bf0c1a6").then(next)
    },
  },
  {
    name: "v-08379716",
    path: "/java/SpringBoot.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-08379716").then(next)
    },
  },
  {
    name: "v-b707bd94",
    path: "/java/execption.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b707bd94").then(next)
    },
  },
  {
    name: "v-79c47140",
    path: "/java/java_base.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-79c47140").then(next)
    },
  },
  {
    name: "v-42289d2c",
    path: "/java/juc.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-42289d2c").then(next)
    },
  },
  {
    name: "v-adbc61e8",
    path: "/java/SpringCloud.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-adbc61e8").then(next)
    },
  },
  {
    name: "v-3489f616",
    path: "/java/lambda.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3489f616").then(next)
    },
  },
  {
    name: "v-8a6bda54",
    path: "/java/spring.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8a6bda54").then(next)
    },
  },
  {
    name: "v-7d3bd624",
    path: "/java/%E4%BB%A3%E7%A0%81%E8%A7%84%E8%8C%83.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7d3bd624").then(next)
    },
  },
  {
    path: "/java/代码规范.html",
    redirect: "/java/%E4%BB%A3%E7%A0%81%E8%A7%84%E8%8C%83.html"
  },
  {
    path: "/java/代码规范.html",
    redirect: "/java/%E4%BB%A3%E7%A0%81%E8%A7%84%E8%8C%83.html"
  },
  {
    name: "v-f2c5abd2",
    path: "/java/%E6%80%BB%E7%BB%93%E7%9A%84%E9%A2%98%E7%9B%AE.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f2c5abd2").then(next)
    },
  },
  {
    path: "/java/总结的题目.html",
    redirect: "/java/%E6%80%BB%E7%BB%93%E7%9A%84%E9%A2%98%E7%9B%AE.html"
  },
  {
    path: "/java/总结的题目.html",
    redirect: "/java/%E6%80%BB%E7%BB%93%E7%9A%84%E9%A2%98%E7%9B%AE.html"
  },
  {
    name: "v-793cbd02",
    path: "/%E5%B7%A5%E4%BD%9C%E7%BB%8F%E9%AA%8C/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-793cbd02").then(next)
    },
  },
  {
    path: "/工作经验/",
    redirect: "/%E5%B7%A5%E4%BD%9C%E7%BB%8F%E9%AA%8C/"
  },
  {
    path: "/%E5%B7%A5%E4%BD%9C%E7%BB%8F%E9%AA%8C/index.html",
    redirect: "/%E5%B7%A5%E4%BD%9C%E7%BB%8F%E9%AA%8C/"
  },
  {
    path: "/工作经验/",
    redirect: "/%E5%B7%A5%E4%BD%9C%E7%BB%8F%E9%AA%8C/"
  },
  {
    name: "v-ad270dae",
    path: "/%E5%B7%A5%E4%BD%9C%E7%BB%8F%E9%AA%8C/experience.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ad270dae").then(next)
    },
  },
  {
    path: "/工作经验/experience.html",
    redirect: "/%E5%B7%A5%E4%BD%9C%E7%BB%8F%E9%AA%8C/experience.html"
  },
  {
    path: "/工作经验/experience.html",
    redirect: "/%E5%B7%A5%E4%BD%9C%E7%BB%8F%E9%AA%8C/experience.html"
  },
  {
    name: "v-54b92787",
    path: "/java/%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-54b92787").then(next)
    },
  },
  {
    path: "/java/设计模式.html",
    redirect: "/java/%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F.html"
  },
  {
    path: "/java/设计模式.html",
    redirect: "/java/%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F.html"
  },
  {
    name: "v-fe0d4732",
    path: "/%E5%B7%A5%E4%BD%9C%E7%BB%8F%E9%AA%8C/problem.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fe0d4732").then(next)
    },
  },
  {
    path: "/工作经验/problem.html",
    redirect: "/%E5%B7%A5%E4%BD%9C%E7%BB%8F%E9%AA%8C/problem.html"
  },
  {
    path: "/工作经验/problem.html",
    redirect: "/%E5%B7%A5%E4%BD%9C%E7%BB%8F%E9%AA%8C/problem.html"
  },
  {
    name: "v-46efced7",
    path: "/%E5%B7%A5%E4%BD%9C%E7%BB%8F%E9%AA%8C/%E5%AE%9E%E7%94%A8%E7%9A%84%E7%B1%BB.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-46efced7").then(next)
    },
  },
  {
    path: "/工作经验/实用的类.html",
    redirect: "/%E5%B7%A5%E4%BD%9C%E7%BB%8F%E9%AA%8C/%E5%AE%9E%E7%94%A8%E7%9A%84%E7%B1%BB.html"
  },
  {
    path: "/工作经验/实用的类.html",
    redirect: "/%E5%B7%A5%E4%BD%9C%E7%BB%8F%E9%AA%8C/%E5%AE%9E%E7%94%A8%E7%9A%84%E7%B1%BB.html"
  },
  {
    name: "v-4857bada",
    path: "/%E5%B7%A5%E4%BD%9C%E7%BB%8F%E9%AA%8C/%E7%9F%A5%E8%AF%86%E7%A7%AF%E7%B4%AF.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4857bada").then(next)
    },
  },
  {
    path: "/工作经验/知识积累.html",
    redirect: "/%E5%B7%A5%E4%BD%9C%E7%BB%8F%E9%AA%8C/%E7%9F%A5%E8%AF%86%E7%A7%AF%E7%B4%AF.html"
  },
  {
    path: "/工作经验/知识积累.html",
    redirect: "/%E5%B7%A5%E4%BD%9C%E7%BB%8F%E9%AA%8C/%E7%9F%A5%E8%AF%86%E7%A7%AF%E7%B4%AF.html"
  },
  {
    name: "v-f307ae8e",
    path: "/%E6%93%8D%E4%BD%9C/Git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f307ae8e").then(next)
    },
  },
  {
    path: "/操作/Git.html",
    redirect: "/%E6%93%8D%E4%BD%9C/Git.html"
  },
  {
    path: "/操作/Git.html",
    redirect: "/%E6%93%8D%E4%BD%9C/Git.html"
  },
  {
    name: "v-736836c7",
    path: "/%E6%93%8D%E4%BD%9C/Maven.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-736836c7").then(next)
    },
  },
  {
    path: "/操作/Maven.html",
    redirect: "/%E6%93%8D%E4%BD%9C/Maven.html"
  },
  {
    path: "/操作/Maven.html",
    redirect: "/%E6%93%8D%E4%BD%9C/Maven.html"
  },
  {
    name: "v-8b0ef360",
    path: "/%E6%93%8D%E4%BD%9C/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8b0ef360").then(next)
    },
  },
  {
    path: "/操作/",
    redirect: "/%E6%93%8D%E4%BD%9C/"
  },
  {
    path: "/%E6%93%8D%E4%BD%9C/index.html",
    redirect: "/%E6%93%8D%E4%BD%9C/"
  },
  {
    path: "/操作/",
    redirect: "/%E6%93%8D%E4%BD%9C/"
  },
  {
    name: "v-776e63bb",
    path: "/%E6%93%8D%E4%BD%9C/github-CICD.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-776e63bb").then(next)
    },
  },
  {
    path: "/操作/github-CICD.html",
    redirect: "/%E6%93%8D%E4%BD%9C/github-CICD.html"
  },
  {
    path: "/操作/github-CICD.html",
    redirect: "/%E6%93%8D%E4%BD%9C/github-CICD.html"
  },
  {
    name: "v-7f67163b",
    path: "/%E6%93%8D%E4%BD%9C/idea%E5%B8%B8%E7%94%A8%E8%AE%BE%E7%BD%AE.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f67163b").then(next)
    },
  },
  {
    path: "/操作/idea常用设置.html",
    redirect: "/%E6%93%8D%E4%BD%9C/idea%E5%B8%B8%E7%94%A8%E8%AE%BE%E7%BD%AE.html"
  },
  {
    path: "/操作/idea常用设置.html",
    redirect: "/%E6%93%8D%E4%BD%9C/idea%E5%B8%B8%E7%94%A8%E8%AE%BE%E7%BD%AE.html"
  },
  {
    name: "v-70e21272",
    path: "/%E6%93%8D%E4%BD%9C/npm.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-70e21272").then(next)
    },
  },
  {
    path: "/操作/npm.html",
    redirect: "/%E6%93%8D%E4%BD%9C/npm.html"
  },
  {
    path: "/操作/npm.html",
    redirect: "/%E6%93%8D%E4%BD%9C/npm.html"
  },
  {
    name: "v-3a37e33d",
    path: "/%E6%93%8D%E4%BD%9C/other.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3a37e33d").then(next)
    },
  },
  {
    path: "/操作/other.html",
    redirect: "/%E6%93%8D%E4%BD%9C/other.html"
  },
  {
    path: "/操作/other.html",
    redirect: "/%E6%93%8D%E4%BD%9C/other.html"
  },
  {
    name: "v-296c8a81",
    path: "/%E6%93%8D%E4%BD%9C/sql.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-296c8a81").then(next)
    },
  },
  {
    path: "/操作/sql.html",
    redirect: "/%E6%93%8D%E4%BD%9C/sql.html"
  },
  {
    path: "/操作/sql.html",
    redirect: "/%E6%93%8D%E4%BD%9C/sql.html"
  },
  {
    name: "v-ebc45e8a",
    path: "/%E6%93%8D%E4%BD%9C/vuepress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ebc45e8a").then(next)
    },
  },
  {
    path: "/操作/vuepress.html",
    redirect: "/%E6%93%8D%E4%BD%9C/vuepress.html"
  },
  {
    path: "/操作/vuepress.html",
    redirect: "/%E6%93%8D%E4%BD%9C/vuepress.html"
  },
  {
    name: "v-66509946",
    path: "/%E6%93%8D%E4%BD%9C/%E8%BD%AF%E4%BB%B6%E6%8F%92%E4%BB%B6%E5%AE%89%E8%A3%85.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-66509946").then(next)
    },
  },
  {
    path: "/操作/软件插件安装.html",
    redirect: "/%E6%93%8D%E4%BD%9C/%E8%BD%AF%E4%BB%B6%E6%8F%92%E4%BB%B6%E5%AE%89%E8%A3%85.html"
  },
  {
    path: "/操作/软件插件安装.html",
    redirect: "/%E6%93%8D%E4%BD%9C/%E8%BD%AF%E4%BB%B6%E6%8F%92%E4%BB%B6%E5%AE%89%E8%A3%85.html"
  },
  {
    name: "v-19ce95c4",
    path: "/%E6%95%B0%E6%8D%AE%E5%BA%93/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-19ce95c4").then(next)
    },
  },
  {
    path: "/数据库/",
    redirect: "/%E6%95%B0%E6%8D%AE%E5%BA%93/"
  },
  {
    path: "/%E6%95%B0%E6%8D%AE%E5%BA%93/index.html",
    redirect: "/%E6%95%B0%E6%8D%AE%E5%BA%93/"
  },
  {
    path: "/数据库/",
    redirect: "/%E6%95%B0%E6%8D%AE%E5%BA%93/"
  },
  {
    name: "v-5a249e80",
    path: "/%E6%95%B0%E6%8D%AE%E5%BA%93/mvcc/MVCC%E5%A4%9A%E7%89%88%E6%9C%AC%E5%B9%B6%E5%8F%91%E6%8E%A7%E5%88%B6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5a249e80").then(next)
    },
  },
  {
    path: "/数据库/mvcc/MVCC多版本并发控制.html",
    redirect: "/%E6%95%B0%E6%8D%AE%E5%BA%93/mvcc/MVCC%E5%A4%9A%E7%89%88%E6%9C%AC%E5%B9%B6%E5%8F%91%E6%8E%A7%E5%88%B6.html"
  },
  {
    path: "/数据库/mvcc/MVCC多版本并发控制.html",
    redirect: "/%E6%95%B0%E6%8D%AE%E5%BA%93/mvcc/MVCC%E5%A4%9A%E7%89%88%E6%9C%AC%E5%B9%B6%E5%8F%91%E6%8E%A7%E5%88%B6.html"
  },
  {
    name: "v-aca03b5a",
    path: "/%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-aca03b5a").then(next)
    },
  },
  {
    path: "/源码解析/",
    redirect: "/%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90/"
  },
  {
    path: "/%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90/index.html",
    redirect: "/%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90/"
  },
  {
    path: "/源码解析/",
    redirect: "/%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90/"
  },
  {
    name: "v-74764301",
    path: "/%E6%95%B0%E6%8D%AE%E5%BA%93/mysql.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-74764301").then(next)
    },
  },
  {
    path: "/数据库/mysql.html",
    redirect: "/%E6%95%B0%E6%8D%AE%E5%BA%93/mysql.html"
  },
  {
    path: "/数据库/mysql.html",
    redirect: "/%E6%95%B0%E6%8D%AE%E5%BA%93/mysql.html"
  },
  {
    name: "v-d642f210",
    path: "/%E7%A8%8B%E5%BA%8F%E5%91%98%E8%8B%B1%E8%AF%AD/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d642f210").then(next)
    },
  },
  {
    path: "/程序员英语/",
    redirect: "/%E7%A8%8B%E5%BA%8F%E5%91%98%E8%8B%B1%E8%AF%AD/"
  },
  {
    path: "/%E7%A8%8B%E5%BA%8F%E5%91%98%E8%8B%B1%E8%AF%AD/index.html",
    redirect: "/%E7%A8%8B%E5%BA%8F%E5%91%98%E8%8B%B1%E8%AF%AD/"
  },
  {
    path: "/程序员英语/",
    redirect: "/%E7%A8%8B%E5%BA%8F%E5%91%98%E8%8B%B1%E8%AF%AD/"
  },
  {
    name: "v-15a22396",
    path: "/%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90/springboot%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15a22396").then(next)
    },
  },
  {
    path: "/源码解析/springboot源码解析.html",
    redirect: "/%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90/springboot%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90.html"
  },
  {
    path: "/源码解析/springboot源码解析.html",
    redirect: "/%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90/springboot%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90.html"
  },
  {
    name: "v-14c17520",
    path: "/%E7%A8%8B%E5%BA%8F%E5%91%98%E8%8B%B1%E8%AF%AD/%E7%A8%8B%E5%BA%8F%E5%91%98%E8%8B%B1%E8%AF%AD.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-14c17520").then(next)
    },
  },
  {
    path: "/程序员英语/程序员英语.html",
    redirect: "/%E7%A8%8B%E5%BA%8F%E5%91%98%E8%8B%B1%E8%AF%AD/%E7%A8%8B%E5%BA%8F%E5%91%98%E8%8B%B1%E8%AF%AD.html"
  },
  {
    path: "/程序员英语/程序员英语.html",
    redirect: "/%E7%A8%8B%E5%BA%8F%E5%91%98%E8%8B%B1%E8%AF%AD/%E7%A8%8B%E5%BA%8F%E5%91%98%E8%8B%B1%E8%AF%AD.html"
  },
  {
    name: "v-f761329e",
    path: "/%E7%AE%97%E6%B3%95%E4%BD%93%E7%B3%BB/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f761329e").then(next)
    },
  },
  {
    path: "/算法体系/",
    redirect: "/%E7%AE%97%E6%B3%95%E4%BD%93%E7%B3%BB/"
  },
  {
    path: "/%E7%AE%97%E6%B3%95%E4%BD%93%E7%B3%BB/index.html",
    redirect: "/%E7%AE%97%E6%B3%95%E4%BD%93%E7%B3%BB/"
  },
  {
    path: "/算法体系/",
    redirect: "/%E7%AE%97%E6%B3%95%E4%BD%93%E7%B3%BB/"
  },
  {
    name: "v-9ee2c794",
    path: "/%E7%AE%97%E6%B3%95%E4%BD%93%E7%B3%BB/%E7%AE%97%E6%B3%95%E5%9F%BA%E7%A1%80.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9ee2c794").then(next)
    },
  },
  {
    path: "/算法体系/算法基础.html",
    redirect: "/%E7%AE%97%E6%B3%95%E4%BD%93%E7%B3%BB/%E7%AE%97%E6%B3%95%E5%9F%BA%E7%A1%80.html"
  },
  {
    path: "/算法体系/算法基础.html",
    redirect: "/%E7%AE%97%E6%B3%95%E4%BD%93%E7%B3%BB/%E7%AE%97%E6%B3%95%E5%9F%BA%E7%A1%80.html"
  },
  {
    name: "v-1fcafc36",
    path: "/%E9%A1%B9%E7%9B%AE%E7%BB%8F%E9%AA%8C/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1fcafc36").then(next)
    },
  },
  {
    path: "/项目经验/",
    redirect: "/%E9%A1%B9%E7%9B%AE%E7%BB%8F%E9%AA%8C/"
  },
  {
    path: "/%E9%A1%B9%E7%9B%AE%E7%BB%8F%E9%AA%8C/index.html",
    redirect: "/%E9%A1%B9%E7%9B%AE%E7%BB%8F%E9%AA%8C/"
  },
  {
    path: "/项目经验/",
    redirect: "/%E9%A1%B9%E7%9B%AE%E7%BB%8F%E9%AA%8C/"
  },
  {
    name: "v-595530e4",
    path: "/%E9%A1%B9%E7%9B%AE%E7%BB%8F%E9%AA%8C/%E5%BE%AE%E6%9C%8D%E5%8A%A1%E9%A1%B9%E7%9B%AE%E6%9E%B6%E6%9E%84.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-595530e4").then(next)
    },
  },
  {
    path: "/项目经验/微服务项目架构.html",
    redirect: "/%E9%A1%B9%E7%9B%AE%E7%BB%8F%E9%AA%8C/%E5%BE%AE%E6%9C%8D%E5%8A%A1%E9%A1%B9%E7%9B%AE%E6%9E%B6%E6%9E%84.html"
  },
  {
    path: "/项目经验/微服务项目架构.html",
    redirect: "/%E9%A1%B9%E7%9B%AE%E7%BB%8F%E9%AA%8C/%E5%BE%AE%E6%9C%8D%E5%8A%A1%E9%A1%B9%E7%9B%AE%E6%9E%B6%E6%9E%84.html"
  },
  {
    name: "v-6d50f9da",
    path: "/%E9%A1%B9%E7%9B%AE%E7%BB%8F%E9%AA%8C/%E6%9C%8D%E5%8A%A1%E6%8B%86%E5%88%86-%E6%8E%A5%E5%8F%A3%E8%AE%BE%E8%AE%A1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6d50f9da").then(next)
    },
  },
  {
    path: "/项目经验/服务拆分-接口设计.html",
    redirect: "/%E9%A1%B9%E7%9B%AE%E7%BB%8F%E9%AA%8C/%E6%9C%8D%E5%8A%A1%E6%8B%86%E5%88%86-%E6%8E%A5%E5%8F%A3%E8%AE%BE%E8%AE%A1.html"
  },
  {
    path: "/项目经验/服务拆分-接口设计.html",
    redirect: "/%E9%A1%B9%E7%9B%AE%E7%BB%8F%E9%AA%8C/%E6%9C%8D%E5%8A%A1%E6%8B%86%E5%88%86-%E6%8E%A5%E5%8F%A3%E8%AE%BE%E8%AE%A1.html"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]