/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "冯手力-java学习之路",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/touxiang.jpg",
        "tagline": null,
        "actionText": "快速上手 →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "java核心知识",
            "details": "多线程与高并发,JVM调优,设计模式,Redis,zooKeeper,sql调优等."
          }
        ],
        "footer": "....."
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-5b3139b6",
      "path": "/"
    },
    {
      "title": "Kafka",
      "frontmatter": {},
      "regularPath": "/java/Kafka.html",
      "relativePath": "java/Kafka.md",
      "key": "v-17bf8350",
      "path": "/java/Kafka.html",
      "headers": [
        {
          "level": 2,
          "title": "图示",
          "slug": "图示"
        }
      ]
    },
    {
      "title": "java底层基础知识",
      "frontmatter": {},
      "regularPath": "/java/",
      "relativePath": "java/README.md",
      "key": "v-3f7e1856",
      "path": "/java/"
    },
    {
      "title": "Redis",
      "frontmatter": {},
      "regularPath": "/java/Redis.html",
      "relativePath": "java/Redis.md",
      "key": "v-2bf0c1a6",
      "path": "/java/Redis.html",
      "headers": [
        {
          "level": 2,
          "title": "一.redis知识点总结",
          "slug": "一-redis知识点总结"
        },
        {
          "level": 2,
          "title": "1.redis是单线程吗",
          "slug": "_1-redis是单线程吗"
        },
        {
          "level": 2,
          "title": "2.击穿,穿透,雪崩.",
          "slug": "_2-击穿-穿透-雪崩"
        },
        {
          "level": 2,
          "title": "3.AKF分治",
          "slug": "_3-akf分治"
        },
        {
          "level": 2,
          "title": "4.Redis和ZooKeeper怎么选",
          "slug": "_4-redis和zookeeper怎么选"
        },
        {
          "level": 2,
          "title": "二.redis系统学习",
          "slug": "二-redis系统学习"
        },
        {
          "level": 2,
          "title": "1.什么是Redis?",
          "slug": "_1-什么是redis"
        },
        {
          "level": 2,
          "title": "击穿,穿透,雪崩",
          "slug": "击穿-穿透-雪崩"
        },
        {
          "level": 3,
          "title": "1.击穿",
          "slug": "_1-击穿"
        },
        {
          "level": 3,
          "title": "2. 穿透",
          "slug": "_2-穿透"
        },
        {
          "level": 3,
          "title": "3.雪崩",
          "slug": "_3-雪崩"
        },
        {
          "level": 3,
          "title": "要有全局感",
          "slug": "要有全局感"
        },
        {
          "level": 2,
          "title": "redis面试经验",
          "slug": "redis面试经验"
        },
        {
          "level": 3,
          "title": "redis常见面试题解析",
          "slug": "redis常见面试题解析"
        }
      ]
    },
    {
      "title": "SpringBoot",
      "frontmatter": {},
      "regularPath": "/java/SpringBoot.html",
      "relativePath": "java/SpringBoot.md",
      "key": "v-08379716",
      "path": "/java/SpringBoot.html",
      "headers": [
        {
          "level": 2,
          "title": "一.官网",
          "slug": "一-官网"
        },
        {
          "level": 2,
          "title": "二.SpringBoot是什么",
          "slug": "二-springboot是什么"
        },
        {
          "level": 2,
          "title": "三.注解",
          "slug": "三-注解"
        },
        {
          "level": 2,
          "title": "四.配置文件位置优先级及细节&常见问题",
          "slug": "四-配置文件位置优先级及细节-常见问题"
        },
        {
          "level": 3,
          "title": "递减优先级",
          "slug": "递减优先级"
        },
        {
          "level": 3,
          "title": "细节",
          "slug": "细节"
        },
        {
          "level": 3,
          "title": "应用",
          "slug": "应用"
        },
        {
          "level": 3,
          "title": "常见问题",
          "slug": "常见问题"
        },
        {
          "level": 2,
          "title": "五.SpringBoot开发",
          "slug": "五-springboot开发"
        },
        {
          "level": 3,
          "title": "1.整合servlet",
          "slug": "_1-整合servlet"
        },
        {
          "level": 3,
          "title": "2.静态资源的配置",
          "slug": "_2-静态资源的配置"
        },
        {
          "level": 3,
          "title": "3.springmvc的扩展",
          "slug": "_3-springmvc的扩展"
        },
        {
          "level": 2,
          "title": "六.Thymeleaf",
          "slug": "六-thymeleaf"
        },
        {
          "level": 3,
          "title": "1、thymeleaf的介绍",
          "slug": "_1、thymeleaf的介绍"
        },
        {
          "level": 3,
          "title": "2、thymeleaf使用模板",
          "slug": "_2、thymeleaf使用模板"
        },
        {
          "level": 3,
          "title": "3、标准表达式语法",
          "slug": "_3、标准表达式语法"
        },
        {
          "level": 3,
          "title": "4、thymeleaf实例演示",
          "slug": "_4、thymeleaf实例演示"
        },
        {
          "level": 3,
          "title": "5、国际化的配置",
          "slug": "_5、国际化的配置"
        },
        {
          "level": 2,
          "title": "七.springboot配置数据源",
          "slug": "七-springboot配置数据源"
        },
        {
          "level": 3,
          "title": "1、JDBC",
          "slug": "_1、jdbc"
        },
        {
          "level": 3,
          "title": "2、自定义数据源DruidDataSource",
          "slug": "_2、自定义数据源druiddatasource"
        },
        {
          "level": 3,
          "title": "3、springboot配置多数据源并动态切换",
          "slug": "_3、springboot配置多数据源并动态切换"
        },
        {
          "level": 3,
          "title": "4、springboot整合mybatis",
          "slug": "_4、springboot整合mybatis"
        },
        {
          "level": 3,
          "title": "5.Mybatis自动生成插件",
          "slug": "_5-mybatis自动生成插件"
        },
        {
          "level": 3,
          "title": "官方示例",
          "slug": "官方示例"
        },
        {
          "level": 3,
          "title": "6.图形化",
          "slug": "_6-图形化"
        },
        {
          "level": 3,
          "title": "7.分页查询-PageHelper",
          "slug": "_7-分页查询-pagehelper"
        },
        {
          "level": 2,
          "title": "八.SpringData Jpa进阶使用",
          "slug": "八-springdata-jpa进阶使用"
        },
        {
          "level": 3,
          "title": "1.使用场景",
          "slug": "_1-使用场景"
        },
        {
          "level": 3,
          "title": "2.控制台显示sql语句",
          "slug": "_2-控制台显示sql语句"
        },
        {
          "level": 3,
          "title": "3.自定义接口",
          "slug": "_3-自定义接口"
        },
        {
          "level": 3,
          "title": "4.自定义SQL - @Query",
          "slug": "_4-自定义sql-query"
        }
      ]
    },
    {
      "title": "java关键字",
      "frontmatter": {},
      "regularPath": "/java/java_base.html",
      "relativePath": "java/java_base.md",
      "key": "v-79c47140",
      "path": "/java/java_base.html",
      "headers": [
        {
          "level": 2,
          "title": "11",
          "slug": "_11"
        },
        {
          "level": 2,
          "title": "22",
          "slug": "_22"
        },
        {
          "level": 3,
          "title": "333",
          "slug": "_333"
        }
      ]
    },
    {
      "title": "SpringCloud学习",
      "frontmatter": {},
      "regularPath": "/java/SpringCloud.html",
      "relativePath": "java/SpringCloud.md",
      "key": "v-adbc61e8",
      "path": "/java/SpringCloud.html",
      "headers": [
        {
          "level": 2,
          "title": "SpringCloud替代实现",
          "slug": "springcloud替代实现"
        },
        {
          "level": 2,
          "title": "SpringCloud -> Alibaba",
          "slug": "springcloud-alibaba"
        },
        {
          "level": 2,
          "title": "组件",
          "slug": "组件"
        },
        {
          "level": 2,
          "title": "第一阶段Spring Cloud技术点",
          "slug": "第一阶段spring-cloud技术点"
        },
        {
          "level": 2,
          "title": "服务进化概述:",
          "slug": "服务进化概述"
        },
        {
          "level": 3,
          "title": "单体应用",
          "slug": "单体应用"
        },
        {
          "level": 3,
          "title": "SOA-Service-Oriented Architecture-面向服务架构",
          "slug": "soa-service-oriented-architecture-面向服务架构"
        },
        {
          "level": 3,
          "title": "微服务",
          "slug": "微服务"
        },
        {
          "level": 2,
          "title": "技术选型",
          "slug": "技术选型"
        },
        {
          "level": 2,
          "title": "Spring Cloud",
          "slug": "spring-cloud"
        },
        {
          "level": 3,
          "title": "概念",
          "slug": "概念"
        },
        {
          "level": 3,
          "title": "版本演进",
          "slug": "版本演进"
        },
        {
          "level": 3,
          "title": "整体架构",
          "slug": "整体架构"
        },
        {
          "level": 2,
          "title": "独立微服务编写",
          "slug": "独立微服务编写"
        },
        {
          "level": 3,
          "title": "开发工具",
          "slug": "开发工具"
        },
        {
          "level": 3,
          "title": "目的",
          "slug": "目的"
        },
        {
          "level": 3,
          "title": "代码步骤",
          "slug": "代码步骤"
        },
        {
          "level": 2,
          "title": "=========================",
          "slug": ""
        },
        {
          "level": 2,
          "title": "服务注册与发现",
          "slug": "服务注册与发现"
        },
        {
          "level": 3,
          "title": "Eureka 介绍",
          "slug": "eureka-介绍"
        },
        {
          "level": 3,
          "title": "Eureka功能",
          "slug": "eureka功能"
        },
        {
          "level": 3,
          "title": "Eureka 单节点搭建",
          "slug": "eureka-单节点搭建"
        },
        {
          "level": 3,
          "title": "Eureka高可用",
          "slug": "eureka高可用"
        },
        {
          "level": 3,
          "title": "服务注册",
          "slug": "服务注册"
        },
        {
          "level": 3,
          "title": "Eureka单独使用",
          "slug": "eureka单独使用"
        },
        {
          "level": 3,
          "title": "元数据",
          "slug": "元数据"
        },
        {
          "level": 3,
          "title": "EurekaClient",
          "slug": "eurekaclient"
        },
        {
          "level": 3,
          "title": "自我保护机制",
          "slug": "自我保护机制"
        },
        {
          "level": 2,
          "title": "使用Spring Boot2.x Actuator监控应用",
          "slug": "使用spring-boot2-x-actuator监控应用"
        },
        {
          "level": 3,
          "title": "开启监控",
          "slug": "开启监控"
        },
        {
          "level": 3,
          "title": "默认端点",
          "slug": "默认端点"
        },
        {
          "level": 3,
          "title": "开启所有端点",
          "slug": "开启所有端点"
        },
        {
          "level": 3,
          "title": "特殊端点shutdown",
          "slug": "特殊端点shutdown"
        },
        {
          "level": 3,
          "title": "api端点功能",
          "slug": "api端点功能"
        },
        {
          "level": 3,
          "title": "java代码测试:",
          "slug": "java代码测试"
        },
        {
          "level": 2,
          "title": "安全配置-spring security",
          "slug": "安全配置-spring-security"
        },
        {
          "level": 3,
          "title": "引入安全依赖",
          "slug": "引入安全依赖"
        },
        {
          "level": 3,
          "title": "开启Eureka安全连接",
          "slug": "开启eureka安全连接"
        },
        {
          "level": 3,
          "title": "如果其他服务向eureka注册报错",
          "slug": "如果其他服务向eureka注册报错"
        },
        {
          "level": 2,
          "title": "RestTemplate",
          "slug": "resttemplate"
        },
        {
          "level": 3,
          "title": "依赖注入",
          "slug": "依赖注入"
        },
        {
          "level": 3,
          "title": "get 请求处理",
          "slug": "get-请求处理"
        },
        {
          "level": 3,
          "title": "post 请求处理",
          "slug": "post-请求处理"
        },
        {
          "level": 3,
          "title": "postForLocation",
          "slug": "postforlocation"
        },
        {
          "level": 3,
          "title": "exchange",
          "slug": "exchange"
        },
        {
          "level": 3,
          "title": "拦截器",
          "slug": "拦截器"
        },
        {
          "level": 2,
          "title": "Ribbon",
          "slug": "ribbon"
        },
        {
          "level": 3,
          "title": "两种负载均衡",
          "slug": "两种负载均衡"
        },
        {
          "level": 3,
          "title": "客户端负载均衡",
          "slug": "客户端负载均衡"
        },
        {
          "level": 3,
          "title": "服务端负载均衡",
          "slug": "服务端负载均衡"
        },
        {
          "level": 3,
          "title": "其他",
          "slug": "其他"
        },
        {
          "level": 3,
          "title": "Ribbon组成",
          "slug": "ribbon组成"
        },
        {
          "level": 3,
          "title": "负载均衡算法",
          "slug": "负载均衡算法"
        },
        {
          "level": 3,
          "title": "切换负载均衡策略",
          "slug": "切换负载均衡策略"
        },
        {
          "level": 3,
          "title": "Ribbon脱离Eureka",
          "slug": "ribbon脱离eureka"
        },
        {
          "level": 2,
          "title": "Feign",
          "slug": "feign"
        },
        {
          "level": 3,
          "title": "Feign",
          "slug": "feign-2"
        },
        {
          "level": 3,
          "title": "Feign和OpenFeign的关系",
          "slug": "feign和openfeign的关系"
        },
        {
          "level": 3,
          "title": "声明式服务调用",
          "slug": "声明式服务调用"
        },
        {
          "level": 3,
          "title": "Get和Post",
          "slug": "get和post"
        },
        {
          "level": 3,
          "title": "feign用法完整示例",
          "slug": "feign用法完整示例"
        },
        {
          "level": 3,
          "title": "超时",
          "slug": "超时"
        },
        {
          "level": 3,
          "title": "重试",
          "slug": "重试"
        },
        {
          "level": 3,
          "title": "权限",
          "slug": "权限"
        },
        {
          "level": 3,
          "title": "原理",
          "slug": "原理"
        },
        {
          "level": 3,
          "title": "压缩",
          "slug": "压缩"
        },
        {
          "level": 2,
          "title": "Hystrix",
          "slug": "hystrix"
        },
        {
          "level": 3,
          "title": "hystrix独立使用脱离spring cloud",
          "slug": "hystrix独立使用脱离spring-cloud"
        },
        {
          "level": 3,
          "title": "整合Resttemplate",
          "slug": "整合resttemplate"
        },
        {
          "level": 3,
          "title": "整合Feign-只有一种返回",
          "slug": "整合feign-只有一种返回"
        },
        {
          "level": 3,
          "title": "使用fallbackFactory检查具体错误",
          "slug": "使用fallbackfactory检查具体错误"
        },
        {
          "level": 3,
          "title": "信号量隔离与线程隔离",
          "slug": "信号量隔离与线程隔离"
        },
        {
          "level": 3,
          "title": "开启dashboard",
          "slug": "开启dashboard"
        }
      ]
    },
    {
      "title": "lambda",
      "frontmatter": {},
      "regularPath": "/java/lambda.html",
      "relativePath": "java/lambda.md",
      "key": "v-3489f616",
      "path": "/java/lambda.html",
      "headers": [
        {
          "level": 2,
          "title": "1.重要特性",
          "slug": "_1-重要特性"
        }
      ]
    },
    {
      "title": "JUC",
      "frontmatter": {},
      "regularPath": "/java/juc.html",
      "relativePath": "java/juc.md",
      "key": "v-42289d2c",
      "path": "/java/juc.html",
      "headers": [
        {
          "level": 2,
          "title": "一.线程",
          "slug": "一-线程"
        },
        {
          "level": 3,
          "title": "1.线程启动方式",
          "slug": "_1-线程启动方式"
        },
        {
          "level": 3,
          "title": "2.线程基本方法",
          "slug": "_2-线程基本方法"
        },
        {
          "level": 3,
          "title": "3.线程状态",
          "slug": "_3-线程状态"
        },
        {
          "level": 3,
          "title": "4.线程挂起",
          "slug": "_4-线程挂起"
        },
        {
          "level": 2,
          "title": "二.锁",
          "slug": "二-锁"
        },
        {
          "level": 3,
          "title": "1. synchronized",
          "slug": "_1-synchronized"
        },
        {
          "level": 3,
          "title": "2. ReentrantLock：可重入锁",
          "slug": "_2-reentrantlock-可重入锁"
        },
        {
          "level": 3,
          "title": "3. CountDownLatch：倒数计时器",
          "slug": "_3-countdownlatch-倒数计时器"
        },
        {
          "level": 3,
          "title": "4.CyclicBarrier：循环栅栏",
          "slug": "_4-cyclicbarrier-循环栅栏"
        },
        {
          "level": 3,
          "title": "5.Phaser：阶段栅栏的作用（1.7加入的）",
          "slug": "_5-phaser-阶段栅栏的作用-1-7加入的"
        },
        {
          "level": 3,
          "title": "6.ReentrantReadWriteLock：读写锁",
          "slug": "_6-reentrantreadwritelock-读写锁"
        },
        {
          "level": 3,
          "title": "7.Semaphore：信号灯（限流、收费站）",
          "slug": "_7-semaphore-信号灯-限流、收费站"
        },
        {
          "level": 3,
          "title": "8.Exchanger：两者交换",
          "slug": "_8-exchanger-两者交换"
        },
        {
          "level": 3,
          "title": "9.LockSupport",
          "slug": "_9-locksupport"
        },
        {
          "level": 3,
          "title": "10.Object.wait()、Object.notify()",
          "slug": "_10-object-wait-、object-notify"
        },
        {
          "level": 3,
          "title": "11.AbstractQueuedSynchronizer： AQS",
          "slug": "_11-abstractqueuedsynchronizer-aqs"
        },
        {
          "level": 2,
          "title": "三. volatile",
          "slug": "三-volatile"
        },
        {
          "level": 3,
          "title": "1.java内存模型",
          "slug": "_1-java内存模型"
        },
        {
          "level": 3,
          "title": "2.内存间的交互动作",
          "slug": "_2-内存间的交互动作"
        },
        {
          "level": 3,
          "title": "3.volatile的特点",
          "slug": "_3-volatile的特点"
        },
        {
          "level": 3,
          "title": "4.缓存的一致性协议: MESI",
          "slug": "_4-缓存的一致性协议-mesi"
        },
        {
          "level": 2,
          "title": "四. CAS: 无锁优化,自旋锁,乐观锁",
          "slug": "四-cas-无锁优化-自旋锁-乐观锁"
        },
        {
          "level": 2,
          "title": "1.CAS的问题",
          "slug": "_1-cas的问题"
        },
        {
          "level": 3,
          "title": "2.使用CAS操作的JDK内部类",
          "slug": "_2-使用cas操作的jdk内部类"
        },
        {
          "level": 3,
          "title": "3.LongAdder",
          "slug": "_3-longadder"
        },
        {
          "level": 2,
          "title": "五. 应用:两个线程之间的等待输出",
          "slug": "五-应用-两个线程之间的等待输出"
        },
        {
          "level": 3,
          "title": "1.LockSupport方式",
          "slug": "_1-locksupport方式"
        },
        {
          "level": 3,
          "title": "2.CountDownLatch 方式",
          "slug": "_2-countdownlatch-方式"
        },
        {
          "level": 3,
          "title": "3.Object.wait(),Object.notify()方式",
          "slug": "_3-object-wait-object-notify-方式"
        },
        {
          "level": 3,
          "title": "4.Semaphore(信号)方式",
          "slug": "_4-semaphore-信号-方式"
        },
        {
          "level": 2,
          "title": "六.应用:生产者 消费者问题",
          "slug": "六-应用-生产者-消费者问题"
        },
        {
          "level": 3,
          "title": "1.ReentrantLock方式",
          "slug": "_1-reentrantlock方式"
        },
        {
          "level": 2,
          "title": "七.强软弱虚引用",
          "slug": "七-强软弱虚引用"
        },
        {
          "level": 3,
          "title": "1.概述",
          "slug": "_1-概述"
        },
        {
          "level": 3,
          "title": "2. 强引用",
          "slug": "_2-强引用"
        },
        {
          "level": 3,
          "title": "3. 软引用:SoftReference",
          "slug": "_3-软引用-softreference"
        },
        {
          "level": 3,
          "title": "4. 弱引用:WeakReference",
          "slug": "_4-弱引用-weakreference"
        },
        {
          "level": 3,
          "title": "5. 虚引用:PhantomReference",
          "slug": "_5-虚引用-phantomreference"
        },
        {
          "level": 2,
          "title": "八.ThreadLoacl",
          "slug": "八-threadloacl"
        },
        {
          "level": 3,
          "title": "1. 应用实例",
          "slug": "_1-应用实例"
        },
        {
          "level": 3,
          "title": "2.私有变量存储在哪里",
          "slug": "_2-私有变量存储在哪里"
        },
        {
          "level": 3,
          "title": "3.ThreadLocal内存模型",
          "slug": "_3-threadlocal内存模型"
        },
        {
          "level": 3,
          "title": "4.可能的内存泄漏分析",
          "slug": "_4-可能的内存泄漏分析"
        },
        {
          "level": 3,
          "title": "5.ThreadLocal使用建议",
          "slug": "_5-threadlocal使用建议"
        },
        {
          "level": 3,
          "title": "6.ThreadLocal需要注意的点",
          "slug": "_6-threadlocal需要注意的点"
        },
        {
          "level": 2,
          "title": "九.队列的接口",
          "slug": "九-队列的接口"
        },
        {
          "level": 3,
          "title": "1.Queue:队列",
          "slug": "_1-queue-队列"
        },
        {
          "level": 3,
          "title": "2.Deque:双端队列(extends Queue)",
          "slug": "_2-deque-双端队列-extends-queue"
        },
        {
          "level": 3,
          "title": "3.BlockingQueue:阻塞队列(extends Queue)",
          "slug": "_3-blockingqueue-阻塞队列-extends-queue"
        },
        {
          "level": 3,
          "title": "4.BlockIngDeque:阻塞的双端队列(extends BlockingQueue,Deque)",
          "slug": "_4-blockingdeque-阻塞的双端队列-extends-blockingqueue-deque"
        },
        {
          "level": 3,
          "title": "5.TransferQueue",
          "slug": "_5-transferqueue"
        },
        {
          "level": 2,
          "title": "十.BlockingQueue的实现了",
          "slug": "十-blockingqueue的实现了"
        },
        {
          "level": 3,
          "title": "1.ArrayBlockingQueue",
          "slug": "_1-arrayblockingqueue"
        },
        {
          "level": 3,
          "title": "2. LinkedBlockingQueue",
          "slug": "_2-linkedblockingqueue"
        },
        {
          "level": 3,
          "title": "3.SynchronousQueue",
          "slug": "_3-synchronousqueue"
        },
        {
          "level": 3,
          "title": "4.LinkedTransferQueue",
          "slug": "_4-linkedtransferqueue"
        },
        {
          "level": 3,
          "title": "5.PriorityBlockingQueue",
          "slug": "_5-priorityblockingqueue"
        },
        {
          "level": 3,
          "title": "6.DelayQueue",
          "slug": "_6-delayqueue"
        },
        {
          "level": 2,
          "title": "十一. BlockingDeque的实现类",
          "slug": "十一-blockingdeque的实现类"
        },
        {
          "level": 3,
          "title": "1.LinkedBlockingDeque",
          "slug": "_1-linkedblockingdeque"
        },
        {
          "level": 2,
          "title": "十二.Queue的实现类",
          "slug": "十二-queue的实现类"
        },
        {
          "level": 3,
          "title": "1.PriorityQueue",
          "slug": "_1-priorityqueue"
        },
        {
          "level": 3,
          "title": "2.ConcurrentLinkedQueue",
          "slug": "_2-concurrentlinkedqueue"
        },
        {
          "level": 2,
          "title": "十三.Deque的实现类",
          "slug": "十三-deque的实现类"
        },
        {
          "level": 3,
          "title": "1.ArrayDeque",
          "slug": "_1-arraydeque"
        },
        {
          "level": 3,
          "title": "2.ConcurrentLinkedDeque",
          "slug": "_2-concurrentlinkeddeque"
        },
        {
          "level": 2,
          "title": "十四.其他重要的容器",
          "slug": "十四-其他重要的容器"
        },
        {
          "level": 3,
          "title": "1.ConcurrentHashMap",
          "slug": "_1-concurrenthashmap"
        },
        {
          "level": 3,
          "title": "2.ConcurrentSkipListMap",
          "slug": "_2-concurrentskiplistmap"
        },
        {
          "level": 3,
          "title": "3.ConcurrentSkipListSet",
          "slug": "_3-concurrentskiplistset"
        },
        {
          "level": 3,
          "title": "4.CopyOnWriteArrayList",
          "slug": "_4-copyonwritearraylist"
        },
        {
          "level": 3,
          "title": "5.CopyOnWriteArraySet",
          "slug": "_5-copyonwritearrayset"
        },
        {
          "level": 2,
          "title": "十五.两个线程交替进行",
          "slug": "十五-两个线程交替进行"
        },
        {
          "level": 3,
          "title": "1.SynchronousQueue",
          "slug": "_1-synchronousqueue"
        },
        {
          "level": 3,
          "title": "2.LinkedTransferQueue",
          "slug": "_2-linkedtransferqueue"
        },
        {
          "level": 3,
          "title": "3.ArrayBlockingQueue",
          "slug": "_3-arrayblockingqueue"
        },
        {
          "level": 3,
          "title": "4.Exchanger",
          "slug": "_4-exchanger"
        },
        {
          "level": 3,
          "title": "5.Object.wait(),Object.notify()",
          "slug": "_5-object-wait-object-notify"
        },
        {
          "level": 3,
          "title": "6.LockSupport",
          "slug": "_6-locksupport"
        },
        {
          "level": 3,
          "title": "7.ReentrantLock单锁",
          "slug": "_7-reentrantlock单锁"
        },
        {
          "level": 3,
          "title": "8.ReentrantLock双锁",
          "slug": "_8-reentrantlock双锁"
        },
        {
          "level": 3,
          "title": "9.CAS锁",
          "slug": "_9-cas锁"
        },
        {
          "level": 3,
          "title": "10.AtomicInteger-CAS",
          "slug": "_10-atomicinteger-cas"
        },
        {
          "level": 2,
          "title": "十六.线程池",
          "slug": "十六-线程池"
        },
        {
          "level": 3,
          "title": "1.Executor",
          "slug": "_1-executor"
        },
        {
          "level": 3,
          "title": "2.Callable",
          "slug": "_2-callable"
        },
        {
          "level": 3,
          "title": "3.ExecutorService",
          "slug": "_3-executorservice"
        },
        {
          "level": 3,
          "title": "4.Future",
          "slug": "_4-future"
        },
        {
          "level": 3,
          "title": "5.FutureTask",
          "slug": "_5-futuretask"
        },
        {
          "level": 3,
          "title": "6.CompletableFuture",
          "slug": "_6-completablefuture"
        },
        {
          "level": 3,
          "title": "7.Executors:线程池的工厂",
          "slug": "_7-executors-线程池的工厂"
        },
        {
          "level": 3,
          "title": "8.ThreadPoolExecutor",
          "slug": "_8-threadpoolexecutor"
        },
        {
          "level": 3,
          "title": "9.ForkJoinPool",
          "slug": "_9-forkjoinpool"
        },
        {
          "level": 2,
          "title": "十七.Disruptor",
          "slug": "十七-disruptor"
        },
        {
          "level": 3,
          "title": "1.概述",
          "slug": "_1-概述-6"
        },
        {
          "level": 3,
          "title": "2.Disruptor的特点",
          "slug": "_2-disruptor的特点"
        },
        {
          "level": 3,
          "title": "3.RingBuffer",
          "slug": "_3-ringbuffer"
        },
        {
          "level": 3,
          "title": "4.Disruptor的开发步骤",
          "slug": "_4-disruptor的开发步骤"
        },
        {
          "level": 3,
          "title": "5.事件发布模板",
          "slug": "_5-事件发布模板"
        },
        {
          "level": 3,
          "title": "6.使用EventTranslator发布事件",
          "slug": "_6-使用eventtranslator发布事件"
        },
        {
          "level": 3,
          "title": "7.使用lambda表达式",
          "slug": "_7-使用lambda表达式"
        },
        {
          "level": 3,
          "title": "8.ProducerType生产者线程模式",
          "slug": "_8-producertype生产者线程模式"
        },
        {
          "level": 3,
          "title": "9.等待策略",
          "slug": "_9-等待策略"
        },
        {
          "level": 3,
          "title": "10.消费者异常处理",
          "slug": "_10-消费者异常处理"
        }
      ]
    },
    {
      "title": "开发第一课-代码规范!",
      "frontmatter": {},
      "regularPath": "/java/%E4%BB%A3%E7%A0%81%E8%A7%84%E8%8C%83.html",
      "relativePath": "java/代码规范.md",
      "key": "v-7d3bd624",
      "path": "/java/%E4%BB%A3%E7%A0%81%E8%A7%84%E8%8C%83.html",
      "headers": [
        {
          "level": 2,
          "title": "",
          "slug": "代码不规范-亲人两行泪"
        },
        {
          "level": 3,
          "title": "1.声明常量",
          "slug": "_1-声明常量"
        },
        {
          "level": 3,
          "title": "2.局部变量返回",
          "slug": "_2-局部变量返回"
        },
        {
          "level": 3,
          "title": "3.相同常量返回值",
          "slug": "_3-相同常量返回值"
        },
        {
          "level": 3,
          "title": "4.包路径命名规范",
          "slug": "_4-包路径命名规范"
        }
      ]
    },
    {
      "title": "工作中遇到的各种问题,bug汇总.",
      "frontmatter": {},
      "regularPath": "/%E5%B7%A5%E4%BD%9C%E7%BB%8F%E9%AA%8C/",
      "relativePath": "工作经验/README.md",
      "key": "v-793cbd02",
      "path": "/%E5%B7%A5%E4%BD%9C%E7%BB%8F%E9%AA%8C/"
    },
    {
      "title": "spring知识汇总",
      "frontmatter": {},
      "regularPath": "/java/spring.html",
      "relativePath": "java/spring.md",
      "key": "v-8a6bda54",
      "path": "/java/spring.html",
      "headers": [
        {
          "level": 2,
          "title": "1.谈谈Spring IOC的理解，原理与实现?",
          "slug": "_1-谈谈spring-ioc的理解-原理与实现"
        },
        {
          "level": 2,
          "title": "2.谈一下spring IOC的底层实现",
          "slug": "_2-谈一下spring-ioc的底层实现"
        },
        {
          "level": 2,
          "title": "3.描述一下bean的生命周期 ？",
          "slug": "_3-描述一下bean的生命周期"
        },
        {
          "level": 2,
          "title": "4.Spring 是如何解决循环依赖的问题的？",
          "slug": "_4-spring-是如何解决循环依赖的问题的"
        },
        {
          "level": 2,
          "title": "4.1缓存的放置时间和删除时间",
          "slug": "_4-1缓存的放置时间和删除时间"
        },
        {
          "level": 2,
          "title": "5.Bean Factory与FactoryBean有什么区别？",
          "slug": "_5-bean-factory与factorybean有什么区别"
        },
        {
          "level": 2,
          "title": "6.Spring中用到的设计模式?",
          "slug": "_6-spring中用到的设计模式"
        },
        {
          "level": 2,
          "title": "7.Spring的AOP的底层实现原理?",
          "slug": "_7-spring的aop的底层实现原理"
        },
        {
          "level": 2,
          "title": "8.Spring的事务是如何回滚的?",
          "slug": "_8-spring的事务是如何回滚的"
        },
        {
          "level": 2,
          "title": "9.谈一下spring事务传播？",
          "slug": "_9-谈一下spring事务传播"
        }
      ]
    },
    {
      "title": "总结的题目",
      "frontmatter": {},
      "regularPath": "/java/%E6%80%BB%E7%BB%93%E7%9A%84%E9%A2%98%E7%9B%AE.html",
      "relativePath": "java/总结的题目.md",
      "key": "v-f2c5abd2",
      "path": "/java/%E6%80%BB%E7%BB%93%E7%9A%84%E9%A2%98%E7%9B%AE.html",
      "headers": [
        {
          "level": 2,
          "title": "0.简历上写的一定要会",
          "slug": "_0-简历上写的一定要会"
        },
        {
          "level": 2,
          "title": "1.Spring事务是怎么实现的,事务失效的情况分析",
          "slug": "_1-spring事务是怎么实现的-事务失效的情况分析"
        },
        {
          "level": 2,
          "title": "2.zookeeper的锁如何应用",
          "slug": "_2-zookeeper的锁如何应用"
        },
        {
          "level": 2,
          "title": "3.MySql和Oracle的区别",
          "slug": "_3-mysql和oracle的区别"
        },
        {
          "level": 3,
          "title": "一、宏观上:",
          "slug": "一、宏观上"
        },
        {
          "level": 3,
          "title": "二、微观上:",
          "slug": "二、微观上"
        },
        {
          "level": 2,
          "title": "4.Weblogic和Tomcat的区别",
          "slug": "_4-weblogic和tomcat的区别"
        },
        {
          "level": 2,
          "title": "5.gc有哪些回收器.",
          "slug": "_5-gc有哪些回收器"
        },
        {
          "level": 3,
          "title": "一、串行垃圾回收器",
          "slug": "一、串行垃圾回收器"
        },
        {
          "level": 3,
          "title": "二、并行垃圾回收器",
          "slug": "二、并行垃圾回收器"
        },
        {
          "level": 3,
          "title": "三、CMS收集器",
          "slug": "三、cms收集器"
        },
        {
          "level": 3,
          "title": "四、G1垃圾收集器",
          "slug": "四、g1垃圾收集器"
        },
        {
          "level": 2,
          "title": "6.内存新生代.老年代等",
          "slug": "_6-内存新生代-老年代等"
        },
        {
          "level": 3,
          "title": "JVM--对象什么情况会进入到老年代",
          "slug": "jvm-对象什么情况会进入到老年代"
        },
        {
          "level": 2,
          "title": "7.为什么需要分布式锁",
          "slug": "_7-为什么需要分布式锁"
        },
        {
          "level": 3,
          "title": "什么是分布式锁",
          "slug": "什么是分布式锁"
        },
        {
          "level": 3,
          "title": "为什么需要分布式锁",
          "slug": "为什么需要分布式锁"
        },
        {
          "level": 2,
          "title": "8.工厂,代理模式,好好看看.",
          "slug": "_8-工厂-代理模式-好好看看"
        },
        {
          "level": 2,
          "title": "9.HashMap是线程安全吗,为啥",
          "slug": "_9-hashmap是线程安全吗-为啥"
        },
        {
          "level": 2,
          "title": "10.gc线上调优经验(如果写了会被问)",
          "slug": "_10-gc线上调优经验-如果写了会被问"
        },
        {
          "level": 2,
          "title": "11.说说如果你想用zookeeper怎么用.",
          "slug": "_11-说说如果你想用zookeeper怎么用"
        },
        {
          "level": 2,
          "title": "12.redis和zookeeper的分布式锁有什么区别",
          "slug": "_12-redis和zookeeper的分布式锁有什么区别"
        },
        {
          "level": 3,
          "title": "zookeeper实现分布式锁的原理",
          "slug": "zookeeper实现分布式锁的原理"
        },
        {
          "level": 2,
          "title": "13.Thread和Runnable的顶级父类是什么",
          "slug": "_13-thread和runnable的顶级父类是什么"
        },
        {
          "level": 2,
          "title": "14.spring中用了哪些设计模式",
          "slug": "_14-spring中用了哪些设计模式"
        },
        {
          "level": 2,
          "title": "15.ConcurrentHashMap的链表为什么8个就转为红黑树",
          "slug": "_15-concurrenthashmap的链表为什么8个就转为红黑树"
        },
        {
          "level": 2,
          "title": "16.Innodb和myisam的区别和使用",
          "slug": "_16-innodb和myisam的区别和使用"
        },
        {
          "level": 2,
          "title": "17.map是如何实现的",
          "slug": "_17-map是如何实现的"
        },
        {
          "level": 2,
          "title": "18.红黑树",
          "slug": "_18-红黑树"
        },
        {
          "level": 2,
          "title": "",
          "slug": ""
        },
        {
          "level": 2,
          "title": "19.mysql事务隔离级别",
          "slug": "_19-mysql事务隔离级别"
        },
        {
          "level": 2,
          "title": "20.索引失效的情况,详见sql.md",
          "slug": "_20-索引失效的情况-详见sql-md"
        },
        {
          "level": 2,
          "title": "21.tcp三次握手,四次挥手",
          "slug": "_21-tcp三次握手-四次挥手"
        },
        {
          "level": 2,
          "title": "22.一致性哈希原理",
          "slug": "_22-一致性哈希原理"
        },
        {
          "level": 2,
          "title": "23.Redis数据类型.及实现原理",
          "slug": "_23-redis数据类型-及实现原理"
        },
        {
          "level": 2,
          "title": "24.lambda并行的线程池和java线程池的区别",
          "slug": "_24-lambda并行的线程池和java线程池的区别"
        },
        {
          "level": 2,
          "title": "24.1.java线程池7个参数,四个实现方式,队列和最大线程数执行顺序.",
          "slug": "_24-1-java线程池7个参数-四个实现方式-队列和最大线程数执行顺序"
        },
        {
          "level": 2,
          "title": "25.java中解决了ABA问题的类",
          "slug": "_25-java中解决了aba问题的类"
        },
        {
          "level": 2,
          "title": "26.CAS全拼是什么.他的set的实现细节",
          "slug": "_26-cas全拼是什么-他的set的实现细节"
        },
        {
          "level": 2,
          "title": "27.redis的原子setnx是在哪个版本出现的",
          "slug": "_27-redis的原子setnx是在哪个版本出现的"
        },
        {
          "level": 2,
          "title": "28.redis的set kv nx ex  是怎么保证原子的.",
          "slug": "_28-redis的set-kv-nx-ex-是怎么保证原子的"
        },
        {
          "level": 2,
          "title": "29.mysql如何排查死锁问题.",
          "slug": "_29-mysql如何排查死锁问题"
        },
        {
          "level": 2,
          "title": "30.innodb什么时候表锁,什么时候行锁.",
          "slug": "_30-innodb什么时候表锁-什么时候行锁"
        },
        {
          "level": 2,
          "title": "31.java如何排查死锁.",
          "slug": "_31-java如何排查死锁"
        },
        {
          "level": 2,
          "title": "32.向hashset中插入自定义的类有什么需要注意的.",
          "slug": "_32-向hashset中插入自定义的类有什么需要注意的"
        },
        {
          "level": 2,
          "title": "33.hashMap和hashSet的底层",
          "slug": "_33-hashmap和hashset的底层"
        },
        {
          "level": 2,
          "title": "34.HashSet类是如何实现添加元素保证不重复的",
          "slug": "_34-hashset类是如何实现添加元素保证不重复的"
        },
        {
          "level": 2,
          "title": "35.redis在你的项目中你是怎么用的.redis锁的注意事项.",
          "slug": "_35-redis在你的项目中你是怎么用的-redis锁的注意事项"
        }
      ]
    },
    {
      "title": "设计模式",
      "frontmatter": {},
      "regularPath": "/java/%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F.html",
      "relativePath": "java/设计模式.md",
      "key": "v-54b92787",
      "path": "/java/%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F.html",
      "headers": [
        {
          "level": 2,
          "title": "分类:",
          "slug": "分类"
        },
        {
          "level": 2,
          "title": "我用过的设计模式/实用的设计模式:",
          "slug": "我用过的设计模式-实用的设计模式"
        },
        {
          "level": 2,
          "title": "面向对象六大设计原则",
          "slug": "面向对象六大设计原则"
        },
        {
          "level": 2,
          "title": "1.Singleton 单例模式",
          "slug": "_1-singleton-单例模式"
        },
        {
          "level": 3,
          "title": "1.常用场景.",
          "slug": "_1-常用场景"
        },
        {
          "level": 3,
          "title": "2.实现方式.",
          "slug": "_2-实现方式"
        },
        {
          "level": 3,
          "title": "3.单例模式的好处.",
          "slug": "_3-单例模式的好处"
        },
        {
          "level": 2,
          "title": "2.Strategy 策略模式",
          "slug": "_2-strategy-策略模式"
        },
        {
          "level": 3,
          "title": "1.简单介绍",
          "slug": "_1-简单介绍"
        },
        {
          "level": 3,
          "title": "2.优缺点",
          "slug": "_2-优缺点"
        },
        {
          "level": 3,
          "title": "3.实现方式举例说明:",
          "slug": "_3-实现方式举例说明"
        },
        {
          "level": 3,
          "title": "4.策略模式与state状态模式的区别",
          "slug": "_4-策略模式与state状态模式的区别"
        },
        {
          "level": 2,
          "title": "3.Factory 工厂模式",
          "slug": "_3-factory-工厂模式"
        },
        {
          "level": 3,
          "title": "1.工厂系列",
          "slug": "_1-工厂系列"
        },
        {
          "level": 3,
          "title": "2.具体实现方法",
          "slug": "_2-具体实现方法"
        },
        {
          "level": 3,
          "title": "3.springIOC",
          "slug": "_3-springioc"
        },
        {
          "level": 2,
          "title": "4.Facade 门面",
          "slug": "_4-facade-门面"
        },
        {
          "level": 3,
          "title": "1.门面的理解.",
          "slug": "_1-门面的理解"
        },
        {
          "level": 3,
          "title": "2.图解",
          "slug": "_2-图解"
        },
        {
          "level": 2,
          "title": "5.Mediator 调停者",
          "slug": "_5-mediator-调停者"
        },
        {
          "level": 3,
          "title": "1.图解",
          "slug": "_1-图解"
        },
        {
          "level": 3,
          "title": "2.应用",
          "slug": "_2-应用"
        },
        {
          "level": 3,
          "title": "3.应用思路",
          "slug": "_3-应用思路"
        },
        {
          "level": 2,
          "title": "6.Chain Of Responsibility 责任链模式",
          "slug": "_6-chain-of-responsibility-责任链模式"
        },
        {
          "level": 3,
          "title": "1.定义",
          "slug": "_1-定义"
        },
        {
          "level": 3,
          "title": "2.应用",
          "slug": "_2-应用-2"
        },
        {
          "level": 3,
          "title": "3.实例1",
          "slug": "_3-实例1"
        },
        {
          "level": 3,
          "title": "4.实例2",
          "slug": "_4-实例2"
        },
        {
          "level": 2,
          "title": "7.装饰者 Decorator",
          "slug": "_7-装饰者-decorator"
        },
        {
          "level": 3,
          "title": "1.类图",
          "slug": "_1-类图"
        },
        {
          "level": 3,
          "title": "2.实现方式",
          "slug": "_2-实现方式-2"
        },
        {
          "level": 2,
          "title": "8.Observer 观察者模式",
          "slug": "_8-observer-观察者模式"
        },
        {
          "level": 3,
          "title": "1.类图",
          "slug": "_1-类图-2"
        },
        {
          "level": 3,
          "title": "2.应用场景.",
          "slug": "_2-应用场景"
        },
        {
          "level": 3,
          "title": "3.应用实例",
          "slug": "_3-应用实例"
        },
        {
          "level": 2,
          "title": "9.Composite 组合",
          "slug": "_9-composite-组合"
        },
        {
          "level": 3,
          "title": "1.类图",
          "slug": "_1-类图-3"
        },
        {
          "level": 3,
          "title": "2.应用场景",
          "slug": "_2-应用场景-2"
        },
        {
          "level": 3,
          "title": "3.应用实例",
          "slug": "_3-应用实例-2"
        },
        {
          "level": 2,
          "title": "10.Flyweight 享元 共享元数据",
          "slug": "_10-flyweight-享元-共享元数据"
        },
        {
          "level": 3,
          "title": "1.使用场景",
          "slug": "_1-使用场景"
        },
        {
          "level": 3,
          "title": "2.结合Composite.",
          "slug": "_2-结合composite"
        },
        {
          "level": 3,
          "title": "3.实例应用",
          "slug": "_3-实例应用"
        },
        {
          "level": 2,
          "title": "11.Proxy 代理",
          "slug": "_11-proxy-代理"
        },
        {
          "level": 3,
          "title": "1.静态代理.",
          "slug": "_1-静态代理"
        },
        {
          "level": 3,
          "title": "2.动态代理",
          "slug": "_2-动态代理"
        },
        {
          "level": 3,
          "title": "3.SpringAOP",
          "slug": "_3-springaop"
        },
        {
          "level": 2,
          "title": "12.Iterator 迭代器模式",
          "slug": "_12-iterator-迭代器模式"
        },
        {
          "level": 3,
          "title": "1.实现方式(泛型)",
          "slug": "_1-实现方式-泛型"
        },
        {
          "level": 2,
          "title": "13.Visitor 访问者",
          "slug": "_13-visitor-访问者"
        },
        {
          "level": 3,
          "title": "1.模式的结构与实现",
          "slug": "_1-模式的结构与实现"
        },
        {
          "level": 3,
          "title": "2.应用实例",
          "slug": "_2-应用实例"
        },
        {
          "level": 2,
          "title": "14.Builder 构建者模式",
          "slug": "_14-builder-构建者模式"
        },
        {
          "level": 3,
          "title": "1.作用和特点",
          "slug": "_1-作用和特点"
        },
        {
          "level": 3,
          "title": "2.实例演示1",
          "slug": "_2-实例演示1"
        },
        {
          "level": 3,
          "title": "3.实例2",
          "slug": "_3-实例2"
        },
        {
          "level": 3,
          "title": "4.建造者模式和工厂模式的区别",
          "slug": "_4-建造者模式和工厂模式的区别"
        },
        {
          "level": 2,
          "title": "15.Adapter(Wrapper) 适配器模式",
          "slug": "_15-adapter-wrapper-适配器模式"
        },
        {
          "level": 3,
          "title": "1.图例",
          "slug": "_1-图例"
        },
        {
          "level": 3,
          "title": "2.应用",
          "slug": "_2-应用-3"
        },
        {
          "level": 3,
          "title": "3.误区",
          "slug": "_3-误区"
        },
        {
          "level": 3,
          "title": "4.应用实例",
          "slug": "_4-应用实例"
        },
        {
          "level": 2,
          "title": "16.Bridge 桥接模式",
          "slug": "_16-bridge-桥接模式"
        },
        {
          "level": 3,
          "title": "1.描述",
          "slug": "_1-描述"
        },
        {
          "level": 3,
          "title": "2.实例应用",
          "slug": "_2-实例应用"
        },
        {
          "level": 2,
          "title": "17.Command",
          "slug": "_17-command"
        },
        {
          "level": 3,
          "title": "1.描述",
          "slug": "_1-描述-2"
        },
        {
          "level": 3,
          "title": "2.应用实例",
          "slug": "_2-应用实例-2"
        },
        {
          "level": 2,
          "title": "18.Prototype 原型模式",
          "slug": "_18-prototype-原型模式"
        },
        {
          "level": 3,
          "title": "1.类图",
          "slug": "_1-类图-4"
        },
        {
          "level": 3,
          "title": "2.应用实例",
          "slug": "_2-应用实例-3"
        },
        {
          "level": 2,
          "title": "19.Memento 备忘录模式",
          "slug": "_19-memento-备忘录模式"
        },
        {
          "level": 3,
          "title": "1.类图",
          "slug": "_1-类图-5"
        },
        {
          "level": 3,
          "title": "2.应用实例",
          "slug": "_2-应用实例-4"
        },
        {
          "level": 2,
          "title": "20.TemplateMethod 模板方法",
          "slug": "_20-templatemethod-模板方法"
        },
        {
          "level": 3,
          "title": "1.类图",
          "slug": "_1-类图-6"
        },
        {
          "level": 3,
          "title": "2.应用实例",
          "slug": "_2-应用实例-5"
        },
        {
          "level": 2,
          "title": "21.State 状态模式",
          "slug": "_21-state-状态模式"
        },
        {
          "level": 3,
          "title": "1.类图",
          "slug": "_1-类图-7"
        },
        {
          "level": 3,
          "title": "2.优缺点",
          "slug": "_2-优缺点-2"
        },
        {
          "level": 3,
          "title": "3.模式结构",
          "slug": "_3-模式结构"
        },
        {
          "level": 3,
          "title": "3.应用实例",
          "slug": "_3-应用实例-4"
        },
        {
          "level": 2,
          "title": "22.Intepreter 解释器",
          "slug": "_22-intepreter-解释器"
        }
      ]
    },
    {
      "title": "工作经验",
      "frontmatter": {},
      "regularPath": "/%E5%B7%A5%E4%BD%9C%E7%BB%8F%E9%AA%8C/experience.html",
      "relativePath": "工作经验/experience.md",
      "key": "v-ad270dae",
      "path": "/%E5%B7%A5%E4%BD%9C%E7%BB%8F%E9%AA%8C/experience.html",
      "headers": [
        {
          "level": 2,
          "title": "1.对一张很大的数据库表所有数据进行操作.(千万级别)",
          "slug": "_1-对一张很大的数据库表所有数据进行操作-千万级别"
        }
      ]
    },
    {
      "title": "学习过程中积累的非技术类的知识点",
      "frontmatter": {},
      "regularPath": "/%E5%B7%A5%E4%BD%9C%E7%BB%8F%E9%AA%8C/%E7%9F%A5%E8%AF%86%E7%A7%AF%E7%B4%AF.html",
      "relativePath": "工作经验/知识积累.md",
      "key": "v-4857bada",
      "path": "/%E5%B7%A5%E4%BD%9C%E7%BB%8F%E9%AA%8C/%E7%9F%A5%E8%AF%86%E7%A7%AF%E7%B4%AF.html",
      "headers": [
        {
          "level": 2,
          "title": "1.详解UML图之类图",
          "slug": "_1-详解uml图之类图"
        },
        {
          "level": 3,
          "title": "1.为什么需要类图？类图的作用",
          "slug": "_1-为什么需要类图-类图的作用"
        },
        {
          "level": 3,
          "title": "2.怎么画类图？用什么工具？",
          "slug": "_2-怎么画类图-用什么工具"
        }
      ]
    },
    {
      "title": "git相关操作",
      "frontmatter": {},
      "regularPath": "/%E6%93%8D%E4%BD%9C/Git.html",
      "relativePath": "操作/Git.md",
      "key": "v-f307ae8e",
      "path": "/%E6%93%8D%E4%BD%9C/Git.html",
      "headers": [
        {
          "level": 2,
          "title": "一.添加git的ssh",
          "slug": "一-添加git的ssh"
        },
        {
          "level": 3,
          "title": "1.进入到当前用户的主目录中(指C:user/fengshouli)",
          "slug": "_1-进入到当前用户的主目录中-指c-user-fengshouli"
        },
        {
          "level": 3,
          "title": "2.执行一个命令,生成.ssh目录",
          "slug": "_2-执行一个命令-生成-ssh目录"
        },
        {
          "level": 3,
          "title": "3.操作SSH的key",
          "slug": "_3-操作ssh的key"
        },
        {
          "level": 3,
          "title": "4.对ssh远程地址起别名",
          "slug": "_4-对ssh远程地址起别名"
        },
        {
          "level": 2,
          "title": "二.换台电脑操作同一个git仓库.",
          "slug": "二-换台电脑操作同一个git仓库"
        },
        {
          "level": 3,
          "title": "1.操作流程,以及遇到的问题.",
          "slug": "_1-操作流程-以及遇到的问题"
        },
        {
          "level": 2,
          "title": "二-1提交被拒绝.",
          "slug": "二-1提交被拒绝"
        },
        {
          "level": 2,
          "title": "二-2有些新的文件提交不上去",
          "slug": "二-2有些新的文件提交不上去"
        },
        {
          "level": 2,
          "title": "三.mac添加公钥",
          "slug": "三-mac添加公钥"
        },
        {
          "level": 2,
          "title": "四.将代码提交到git仓库",
          "slug": "四-将代码提交到git仓库"
        },
        {
          "level": 3,
          "title": "1. 先进入项目文件夹，初始化本地仓库",
          "slug": "_1-先进入项目文件夹-初始化本地仓库"
        },
        {
          "level": 3,
          "title": "2. 把文件添加到版本库中，使用命令 git add .添加到暂存区里面去，不要忘记后面的小数点“.”，“.”意为添加文件夹下的所有文件",
          "slug": "_2-把文件添加到版本库中-使用命令-git-add-添加到暂存区里面去-不要忘记后面的小数点-意为添加文件夹下的所有文件"
        },
        {
          "level": 3,
          "title": "3. 将文件提交到本地Git仓库",
          "slug": "_3-将文件提交到本地git仓库"
        },
        {
          "level": 3,
          "title": "4. 登录远程Git新建一个仓库(如果已有可跳过这步)",
          "slug": "_4-登录远程git新建一个仓库-如果已有可跳过这步"
        },
        {
          "level": 3,
          "title": "5. 将本地代码库关联到远程Git库",
          "slug": "_5-将本地代码库关联到远程git库"
        },
        {
          "level": 3,
          "title": "6. 获取远程库文件与本地同步合并",
          "slug": "_6-获取远程库文件与本地同步合并"
        },
        {
          "level": 3,
          "title": "7. 查询需要推送到远程的文件情况",
          "slug": "_7-查询需要推送到远程的文件情况"
        },
        {
          "level": 3,
          "title": "8. 把本地库的内容推送到远程仓库",
          "slug": "_8-把本地库的内容推送到远程仓库"
        },
        {
          "level": 2,
          "title": "五.git命令总结",
          "slug": "五-git命令总结"
        },
        {
          "level": 3,
          "title": "1.常见命令",
          "slug": "_1-常见命令"
        },
        {
          "level": 3,
          "title": "2. Git常用命令列表",
          "slug": "_2-git常用命令列表"
        },
        {
          "level": 3,
          "title": "3.图示!git常见命令",
          "slug": "_3-图示"
        },
        {
          "level": 2,
          "title": "六.vuepress发布在github上如何绑定域名",
          "slug": "六-vuepress发布在github上如何绑定域名"
        },
        {
          "level": 3,
          "title": "1.申请域名.",
          "slug": "_1-申请域名"
        },
        {
          "level": 3,
          "title": "2.项目中增加域名配置文件",
          "slug": "_2-项目中增加域名配置文件"
        },
        {
          "level": 3,
          "title": "3.将域名添加解析.",
          "slug": "_3-将域名添加解析"
        }
      ]
    },
    {
      "title": "Maven",
      "frontmatter": {},
      "regularPath": "/%E6%93%8D%E4%BD%9C/Maven.html",
      "relativePath": "操作/Maven.md",
      "key": "v-736836c7",
      "path": "/%E6%93%8D%E4%BD%9C/Maven.html",
      "headers": [
        {
          "level": 2,
          "title": "一.换源",
          "slug": "一-换源"
        }
      ]
    },
    {
      "title": "一些个操作",
      "frontmatter": {},
      "regularPath": "/%E6%93%8D%E4%BD%9C/",
      "relativePath": "操作/README.md",
      "key": "v-8b0ef360",
      "path": "/%E6%93%8D%E4%BD%9C/"
    },
    {
      "title": "问题记录",
      "frontmatter": {},
      "regularPath": "/%E5%B7%A5%E4%BD%9C%E7%BB%8F%E9%AA%8C/problem.html",
      "relativePath": "工作经验/problem.md",
      "key": "v-fe0d4732",
      "path": "/%E5%B7%A5%E4%BD%9C%E7%BB%8F%E9%AA%8C/problem.html",
      "headers": [
        {
          "level": 2,
          "title": "1.idea使用lombok后,编译提示找不到符号.",
          "slug": "_1-idea使用lombok后-编译提示找不到符号"
        },
        {
          "level": 2,
          "title": "2.weblogic,下载excel等文件,点击乱码.",
          "slug": "_2-weblogic-下载excel等文件-点击乱码"
        },
        {
          "level": 2,
          "title": "3.debug模式跳转到其他同名类中",
          "slug": "_3-debug模式跳转到其他同名类中"
        },
        {
          "level": 2,
          "title": "4.读取config.properties中文乱码",
          "slug": "_4-读取config-properties中文乱码"
        },
        {
          "level": 2,
          "title": "5.mac idea创建maven项目,SpringBoot项目打开就报错",
          "slug": "_5-mac-idea创建maven项目-springboot项目打开就报错"
        },
        {
          "level": 2,
          "title": "6.编译报错.Abnormal build process termination:",
          "slug": "_6-编译报错-abnormal-build-process-termination"
        },
        {
          "level": 2,
          "title": "7.idea2020 启动报Command line is too long.Shorten command line ..",
          "slug": "_7-idea2020-启动报command-line-is-too-long-shorten-command-line"
        }
      ]
    },
    {
      "title": "IDEA的常用设置",
      "frontmatter": {},
      "regularPath": "/%E6%93%8D%E4%BD%9C/idea%E5%B8%B8%E7%94%A8%E8%AE%BE%E7%BD%AE.html",
      "relativePath": "操作/idea常用设置.md",
      "key": "v-7f67163b",
      "path": "/%E6%93%8D%E4%BD%9C/idea%E5%B8%B8%E7%94%A8%E8%AE%BE%E7%BD%AE.html",
      "headers": [
        {
          "level": 3,
          "title": "一.设置表头模板.",
          "slug": "一-设置表头模板"
        },
        {
          "level": 3,
          "title": "二.正文字体和控制台字体控制",
          "slug": "二-正文字体和控制台字体控制"
        }
      ]
    },
    {
      "title": "github-CI/CD",
      "frontmatter": {},
      "regularPath": "/%E6%93%8D%E4%BD%9C/github-CICD.html",
      "relativePath": "操作/github-CICD.md",
      "key": "v-776e63bb",
      "path": "/%E6%93%8D%E4%BD%9C/github-CICD.html",
      "headers": [
        {
          "level": 3,
          "title": "1.为什么需要CI/CD",
          "slug": "_1-为什么需要ci-cd"
        },
        {
          "level": 3,
          "title": "2.使用github-Actions.",
          "slug": "_2-使用github-actions"
        },
        {
          "level": 3,
          "title": "3.带你爬坑",
          "slug": "_3-带你爬坑"
        }
      ]
    },
    {
      "title": "实用的类及注解解析",
      "frontmatter": {},
      "regularPath": "/%E5%B7%A5%E4%BD%9C%E7%BB%8F%E9%AA%8C/%E5%AE%9E%E7%94%A8%E7%9A%84%E7%B1%BB.html",
      "relativePath": "工作经验/实用的类.md",
      "key": "v-46efced7",
      "path": "/%E5%B7%A5%E4%BD%9C%E7%BB%8F%E9%AA%8C/%E5%AE%9E%E7%94%A8%E7%9A%84%E7%B1%BB.html",
      "headers": [
        {
          "level": 2,
          "title": "一.字符串类",
          "slug": "一-字符串类"
        },
        {
          "level": 3,
          "title": "1.StringJoiner",
          "slug": "_1-stringjoiner"
        },
        {
          "level": 2,
          "title": "二.集合类",
          "slug": "二-集合类"
        },
        {
          "level": 2,
          "title": "三.工具类",
          "slug": "三-工具类"
        },
        {
          "level": 3,
          "title": "一.Spring.",
          "slug": "一-spring"
        },
        {
          "level": 3,
          "title": "二.lombok",
          "slug": "二-lombok"
        },
        {
          "level": 3,
          "title": "",
          "slug": ""
        }
      ]
    },
    {
      "title": "经验记录",
      "frontmatter": {},
      "regularPath": "/%E6%93%8D%E4%BD%9C/other.html",
      "relativePath": "操作/other.md",
      "key": "v-3a37e33d",
      "path": "/%E6%93%8D%E4%BD%9C/other.html"
    },
    {
      "title": "sql",
      "frontmatter": {},
      "regularPath": "/%E6%93%8D%E4%BD%9C/sql.html",
      "relativePath": "操作/sql.md",
      "key": "v-296c8a81",
      "path": "/%E6%93%8D%E4%BD%9C/sql.html"
    },
    {
      "title": "软件插件安装",
      "frontmatter": {},
      "regularPath": "/%E6%93%8D%E4%BD%9C/%E8%BD%AF%E4%BB%B6%E6%8F%92%E4%BB%B6%E5%AE%89%E8%A3%85.html",
      "relativePath": "操作/软件插件安装.md",
      "key": "v-66509946",
      "path": "/%E6%93%8D%E4%BD%9C/%E8%BD%AF%E4%BB%B6%E6%8F%92%E4%BB%B6%E5%AE%89%E8%A3%85.html",
      "headers": [
        {
          "level": 2,
          "title": "一.安装postman中文汉化版",
          "slug": "一-安装postman中文汉化版"
        }
      ]
    },
    {
      "title": "vuepress",
      "frontmatter": {},
      "regularPath": "/%E6%93%8D%E4%BD%9C/vuepress.html",
      "relativePath": "操作/vuepress.md",
      "key": "v-ebc45e8a",
      "path": "/%E6%93%8D%E4%BD%9C/vuepress.html",
      "headers": [
        {
          "level": 2,
          "title": "vuepress使用过程中遇到的问题.",
          "slug": "vuepress使用过程中遇到的问题"
        },
        {
          "level": 3,
          "title": "一.具体的官网都有.",
          "slug": "一-具体的官网都有"
        },
        {
          "level": 3,
          "title": "二.启动端口总是8081/无法改变.",
          "slug": "二-启动端口总是8081-无法改变"
        }
      ]
    },
    {
      "title": "数据库相关知识",
      "frontmatter": {},
      "regularPath": "/%E6%95%B0%E6%8D%AE%E5%BA%93/",
      "relativePath": "数据库/README.md",
      "key": "v-19ce95c4",
      "path": "/%E6%95%B0%E6%8D%AE%E5%BA%93/"
    },
    {
      "title": "MySql",
      "frontmatter": {},
      "regularPath": "/%E6%95%B0%E6%8D%AE%E5%BA%93/mysql.html",
      "relativePath": "数据库/mysql.md",
      "key": "v-74764301",
      "path": "/%E6%95%B0%E6%8D%AE%E5%BA%93/mysql.html",
      "headers": [
        {
          "level": 2,
          "title": "一.mysql知识点",
          "slug": "一-mysql知识点"
        },
        {
          "level": 2,
          "title": "1.描述一下数据库事务隔离级别？",
          "slug": "_1-描述一下数据库事务隔离级别"
        },
        {
          "level": 3,
          "title": "1.ACID：",
          "slug": "_1-acid"
        },
        {
          "level": 3,
          "title": "2.数据库的事务隔离级别有四种，",
          "slug": "_2-数据库的事务隔离级别有四种"
        },
        {
          "level": 3,
          "title": "3.各种隔离级别和数据库异常情况对应情况如下：",
          "slug": "_3-各种隔离级别和数据库异常情况对应情况如下"
        },
        {
          "level": 2,
          "title": "2.MVCC-多版本并发控制",
          "slug": "_2-mvcc-多版本并发控制"
        },
        {
          "level": 3,
          "title": "1、MVCC",
          "slug": "_1、mvcc"
        },
        {
          "level": 3,
          "title": "2、当前读--",
          "slug": "_2、当前读-非常重要"
        },
        {
          "level": 3,
          "title": "3、快照读--（提高数据库的并发查询能力）",
          "slug": "_3、快照读-非常重要-提高数据库的并发查询能力"
        },
        {
          "level": 3,
          "title": "4、当前读、快照读、MVCC关系",
          "slug": "_4、当前读、快照读、mvcc关系"
        },
        {
          "level": 3,
          "title": "5、MVCC解决的问题",
          "slug": "_5、mvcc解决的问题"
        },
        {
          "level": 3,
          "title": "6、MVCC实现原理",
          "slug": "_6、mvcc实现原理"
        },
        {
          "level": 3,
          "title": "7、MVCC的整体处理流程",
          "slug": "_7、mvcc的整体处理流程"
        },
        {
          "level": 3,
          "title": "8、RC、RR级别下的InnoDB快照读有什么不同",
          "slug": "_8、rc、rr级别下的innodb快照读有什么不同"
        },
        {
          "level": 2,
          "title": "3.mysql幻读怎么解决的",
          "slug": "_3-mysql幻读怎么解决的"
        },
        {
          "level": 2,
          "title": "4.sql join原理?",
          "slug": "_4-sql-join原理"
        },
        {
          "level": 2,
          "title": "5、说明一下数据库索引原理、底层索引数据结构，叶子节点存储的是什么，索引失效的情况？",
          "slug": "_5、说明一下数据库索引原理、底层索引数据结构-叶子节点存储的是什么-索引失效的情况"
        },
        {
          "level": 3,
          "title": "1.说到索引,一定要说到两个东西",
          "slug": "_1-说到索引-一定要说到两个东西"
        },
        {
          "level": 3,
          "title": "2.失效情况.",
          "slug": "_2-失效情况"
        },
        {
          "level": 2,
          "title": "6.mysql如何做分库分表的？",
          "slug": "_6-mysql如何做分库分表的"
        },
        {
          "level": 2,
          "title": "7.描述一下InnoDB和MyISAM的区别？",
          "slug": "_7-描述一下innodb和myisam的区别"
        },
        {
          "level": 2,
          "title": "8.描述一下聚簇索引和非聚簇索引的区别？",
          "slug": "_8-描述一下聚簇索引和非聚簇索引的区别"
        },
        {
          "level": 2,
          "title": "9.1901课,描述一下mysql主从复制的机制的原理？mysql主从复制主要有几种模式？",
          "slug": "_9-1901课-描述一下mysql主从复制的机制的原理-mysql主从复制主要有几种模式"
        },
        {
          "level": 3,
          "title": "0、为什么需要主从复制？",
          "slug": "_0、为什么需要主从复制"
        },
        {
          "level": 3,
          "title": "1、什么是mysql的主从复制？",
          "slug": "_1、什么是mysql的主从复制"
        },
        {
          "level": 3,
          "title": "2、mysql复制原理",
          "slug": "_2、mysql复制原理"
        },
        {
          "level": 3,
          "title": "3、mysql主从形式",
          "slug": "_3、mysql主从形式"
        },
        {
          "level": 3,
          "title": "4、mysql主从同步延时分析",
          "slug": "_4、mysql主从同步延时分析"
        },
        {
          "level": 2,
          "title": "10.再看2601描述一下mysql的乐观锁和悲观锁，锁的种类？",
          "slug": "_10-再看2601描述一下mysql的乐观锁和悲观锁-锁的种类"
        },
        {
          "level": 2,
          "title": "二.mysql系统学习",
          "slug": "二-mysql系统学习"
        }
      ]
    },
    {
      "title": "npm",
      "frontmatter": {},
      "regularPath": "/%E6%93%8D%E4%BD%9C/npm.html",
      "relativePath": "操作/npm.md",
      "key": "v-70e21272",
      "path": "/%E6%93%8D%E4%BD%9C/npm.html",
      "headers": [
        {
          "level": 2,
          "title": "学习.",
          "slug": "学习"
        },
        {
          "level": 3,
          "title": "一.npm是什么",
          "slug": "一-npm是什么"
        },
        {
          "level": 2,
          "title": "问题.",
          "slug": "问题"
        },
        {
          "level": 3,
          "title": "一.下载很慢",
          "slug": "一-下载很慢"
        }
      ]
    },
    {
      "title": "MVCC多版本并发控制",
      "frontmatter": {},
      "regularPath": "/%E6%95%B0%E6%8D%AE%E5%BA%93/mvcc/MVCC%E5%A4%9A%E7%89%88%E6%9C%AC%E5%B9%B6%E5%8F%91%E6%8E%A7%E5%88%B6.html",
      "relativePath": "数据库/mvcc/MVCC多版本并发控制.md",
      "key": "v-5a249e80",
      "path": "/%E6%95%B0%E6%8D%AE%E5%BA%93/mvcc/MVCC%E5%A4%9A%E7%89%88%E6%9C%AC%E5%B9%B6%E5%8F%91%E6%8E%A7%E5%88%B6.html",
      "headers": [
        {
          "level": 3,
          "title": "1、MVCC",
          "slug": "_1、mvcc"
        },
        {
          "level": 3,
          "title": "2、当前读",
          "slug": "_2、当前读"
        },
        {
          "level": 3,
          "title": "3、快照读（提高数据库的并发查询能力）",
          "slug": "_3、快照读-提高数据库的并发查询能力"
        },
        {
          "level": 3,
          "title": "4、当前读、快照读、MVCC关系",
          "slug": "_4、当前读、快照读、mvcc关系"
        },
        {
          "level": 3,
          "title": "5、MVCC解决的问题",
          "slug": "_5、mvcc解决的问题"
        },
        {
          "level": 3,
          "title": "6、MVCC实现原理",
          "slug": "_6、mvcc实现原理"
        },
        {
          "level": 3,
          "title": "7、MVCC的整体处理流程",
          "slug": "_7、mvcc的整体处理流程"
        },
        {
          "level": 3,
          "title": "8、RC、RR级别下的InnoDB快照读有什么不同",
          "slug": "_8、rc、rr级别下的innodb快照读有什么不同"
        }
      ]
    },
    {
      "title": "记录源码解析过程",
      "frontmatter": {},
      "regularPath": "/%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90/",
      "relativePath": "源码解析/README.md",
      "key": "v-aca03b5a",
      "path": "/%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90/"
    },
    {
      "title": "程序员英语学习",
      "frontmatter": {},
      "regularPath": "/%E7%A8%8B%E5%BA%8F%E5%91%98%E8%8B%B1%E8%AF%AD/",
      "relativePath": "程序员英语/README.md",
      "key": "v-d642f210",
      "path": "/%E7%A8%8B%E5%BA%8F%E5%91%98%E8%8B%B1%E8%AF%AD/"
    },
    {
      "title": "springboot源码解析(一):启动过程",
      "frontmatter": {},
      "regularPath": "/%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90/springboot%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90.html",
      "relativePath": "源码解析/springboot源码解析.md",
      "key": "v-15a22396",
      "path": "/%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90/springboot%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90.html",
      "headers": [
        {
          "level": 2,
          "title": "springboot源码解析(一):启动过程",
          "slug": "springboot源码解析-一-启动过程"
        },
        {
          "level": 3,
          "title": "注:每个版本的源码,会有些许的差异.本文件依赖于2.4.3版本",
          "slug": "注-每个版本的源码-会有些许的差异-本文件依赖于2-4-3版本"
        },
        {
          "level": 3,
          "title": "1、springboot的入口程序",
          "slug": "_1、springboot的入口程序"
        }
      ]
    },
    {
      "title": "程序员英语",
      "frontmatter": {},
      "regularPath": "/%E7%A8%8B%E5%BA%8F%E5%91%98%E8%8B%B1%E8%AF%AD/%E7%A8%8B%E5%BA%8F%E5%91%98%E8%8B%B1%E8%AF%AD.html",
      "relativePath": "程序员英语/程序员英语.md",
      "key": "v-14c17520",
      "path": "/%E7%A8%8B%E5%BA%8F%E5%91%98%E8%8B%B1%E8%AF%AD/%E7%A8%8B%E5%BA%8F%E5%91%98%E8%8B%B1%E8%AF%AD.html",
      "headers": [
        {
          "level": 2,
          "title": "一,错误检查类.",
          "slug": "一-错误检查类"
        },
        {
          "level": 3,
          "title": "1.常量声明:",
          "slug": "_1-常量声明"
        },
        {
          "level": 3,
          "title": "2.返回值",
          "slug": "_2-返回值"
        },
        {
          "level": 2,
          "title": "二.开发工具提示类.",
          "slug": "二-开发工具提示类"
        }
      ]
    },
    {
      "title": "算法体系学习",
      "frontmatter": {},
      "regularPath": "/%E7%AE%97%E6%B3%95%E4%BD%93%E7%B3%BB/",
      "relativePath": "算法体系/README.md",
      "key": "v-f761329e",
      "path": "/%E7%AE%97%E6%B3%95%E4%BD%93%E7%B3%BB/",
      "headers": [
        {
          "level": 2,
          "title": "由浅到深学习算法知识",
          "slug": "由浅到深学习算法知识"
        }
      ]
    },
    {
      "title": "算法基础学习",
      "frontmatter": {},
      "regularPath": "/%E7%AE%97%E6%B3%95%E4%BD%93%E7%B3%BB/%E7%AE%97%E6%B3%95%E5%9F%BA%E7%A1%80.html",
      "relativePath": "算法体系/算法基础.md",
      "key": "v-9ee2c794",
      "path": "/%E7%AE%97%E6%B3%95%E4%BD%93%E7%B3%BB/%E7%AE%97%E6%B3%95%E5%9F%BA%E7%A1%80.html",
      "headers": [
        {
          "level": 2,
          "title": "",
          "slug": ""
        },
        {
          "level": 2,
          "title": "ONE 认识复杂度,对数器,二分法,与异或运算",
          "slug": "one-认识复杂度-对数器-二分法-与异或运算"
        },
        {
          "level": 3,
          "title": "1.时间复杂度是什么,有哪些",
          "slug": "_1-时间复杂度是什么-有哪些"
        },
        {
          "level": 3,
          "title": "2.常见的排序方法比较",
          "slug": "_2-常见的排序方法比较"
        },
        {
          "level": 3,
          "title": "3.常见时间复杂度",
          "slug": "_3-常见时间复杂度"
        },
        {
          "level": 3,
          "title": "4.认识对数器",
          "slug": "_4-认识对数器"
        },
        {
          "level": 3,
          "title": "5.认识异或运算",
          "slug": "_5-认识异或运算"
        },
        {
          "level": 3,
          "title": "6.异或运算实用及常见面试题",
          "slug": "_6-异或运算实用及常见面试题"
        },
        {
          "level": 2,
          "title": "TWO 链表结构,栈,队列,递归行为,哈希表",
          "slug": "two-链表结构-栈-队列-递归行为-哈希表"
        },
        {
          "level": 3,
          "title": "1.单向链表",
          "slug": "_1-单向链表"
        },
        {
          "level": 3,
          "title": "2.双向链表",
          "slug": "_2-双向链表"
        },
        {
          "level": 3,
          "title": "3.链表相关常见题",
          "slug": "_3-链表相关常见题"
        },
        {
          "level": 3,
          "title": "4.栈和队列",
          "slug": "_4-栈和队列"
        },
        {
          "level": 3,
          "title": "5.栈和队列的实际实现",
          "slug": "_5-栈和队列的实际实现"
        },
        {
          "level": 3,
          "title": "6.栈和队列常见题",
          "slug": "_6-栈和队列常见题"
        },
        {
          "level": 3,
          "title": "7.递归",
          "slug": "_7-递归"
        },
        {
          "level": 3,
          "title": "8.哈希表",
          "slug": "_8-哈希表"
        },
        {
          "level": 3,
          "title": "9.有序表",
          "slug": "_9-有序表"
        },
        {
          "level": 2,
          "title": "THREE 归并排序与随机快排",
          "slug": "three-归并排序与随机快排"
        },
        {
          "level": 3,
          "title": "1.归并排序",
          "slug": "_1-归并排序"
        },
        {
          "level": 3,
          "title": "2.快速排序",
          "slug": "_2-快速排序"
        }
      ]
    },
    {
      "title": "readmeß",
      "frontmatter": {},
      "regularPath": "/%E9%A1%B9%E7%9B%AE%E7%BB%8F%E9%AA%8C/",
      "relativePath": "项目经验/README.md",
      "key": "v-1fcafc36",
      "path": "/%E9%A1%B9%E7%9B%AE%E7%BB%8F%E9%AA%8C/"
    },
    {
      "title": "微服务项目结果",
      "frontmatter": {},
      "regularPath": "/%E9%A1%B9%E7%9B%AE%E7%BB%8F%E9%AA%8C/%E5%BE%AE%E6%9C%8D%E5%8A%A1%E9%A1%B9%E7%9B%AE%E6%9E%B6%E6%9E%84.html",
      "relativePath": "项目经验/微服务项目架构.md",
      "key": "v-595530e4",
      "path": "/%E9%A1%B9%E7%9B%AE%E7%BB%8F%E9%AA%8C/%E5%BE%AE%E6%9C%8D%E5%8A%A1%E9%A1%B9%E7%9B%AE%E6%9E%B6%E6%9E%84.html",
      "headers": [
        {
          "level": 2,
          "title": "异常:",
          "slug": "异常"
        }
      ]
    },
    {
      "title": "服务拆分",
      "frontmatter": {},
      "regularPath": "/%E9%A1%B9%E7%9B%AE%E7%BB%8F%E9%AA%8C/%E6%9C%8D%E5%8A%A1%E6%8B%86%E5%88%86-%E6%8E%A5%E5%8F%A3%E8%AE%BE%E8%AE%A1.html",
      "relativePath": "项目经验/服务拆分-接口设计.md",
      "key": "v-6d50f9da",
      "path": "/%E9%A1%B9%E7%9B%AE%E7%BB%8F%E9%AA%8C/%E6%9C%8D%E5%8A%A1%E6%8B%86%E5%88%86-%E6%8E%A5%E5%8F%A3%E8%AE%BE%E8%AE%A1.html",
      "headers": [
        {
          "level": 2,
          "title": "能力层",
          "slug": "能力层"
        },
        {
          "level": 2,
          "title": "第三方:",
          "slug": "第三方"
        },
        {
          "level": 2,
          "title": "面试:",
          "slug": "面试"
        },
        {
          "level": 2,
          "title": "接口设计",
          "slug": "接口设计"
        },
        {
          "level": 2,
          "title": "接口安全",
          "slug": "接口安全"
        }
      ]
    }
  ],
  "themeConfig": {
    "sidebarDepth": 2,
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "操作",
        "link": "/操作/"
      },
      {
        "text": "工作经验",
        "link": "/工作经验/"
      },
      {
        "text": "项目经验",
        "link": "/项目经验/"
      },
      {
        "text": "java知识",
        "link": "/java/"
      },
      {
        "text": "数据库知识",
        "link": "/数据库/"
      },
      {
        "text": "源码解析",
        "link": "/源码解析/"
      },
      {
        "text": "程序员英语",
        "link": "/程序员英语/"
      },
      {
        "text": "算法体系",
        "link": "/算法体系/"
      }
    ],
    "sidebar": {
      "/java/": [
        "",
        "代码规范",
        "java_base",
        "lambda",
        "juc",
        "Kafka",
        "设计模式",
        "Redis",
        "spring",
        "SpringBoot",
        "SpringCloud",
        "总结的题目"
      ],
      "/数据库/": [
        "",
        "mysql"
      ],
      "/操作/": [
        "",
        "Git",
        "github-CICD",
        "npm",
        "Maven",
        "sql",
        "other",
        "软件插件安装"
      ],
      "/工作经验/": [
        "",
        "实用的类",
        "problem",
        "experience",
        "知识积累"
      ],
      "/项目经验/": [
        "",
        "服务拆分-接口设计",
        "微服务项目架构"
      ],
      "/源码解析/": [
        "",
        "springboot源码解析"
      ],
      "/程序员英语/": [
        "",
        "程序员英语"
      ],
      "/算法体系/": [
        "",
        "算法基础.md"
      ]
    }
  }
}