name: vuepress-CI

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm install -D vuepress
      - run: rm -rf dist/
      - run: npm run build:docs
      - run: cp CNAME dist/

          # 发布到 fengshouli.github.io/master
          #- name: Deploy
          #  uses: peaceiris/actions-gh-pages@v2.5.0
          #  env:
          #    ACTIONS_DEPLOY_KEY: ${{secrets.publish}}
          #    PUBLISH_BRANCH: master
          #    PUBLISH_DIR: dist

      # 发布到 fengshouli.github.io/master
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{secrets.publish}}
          EXTERNAL_REPOSITORY: fengshouli/fengshouli.github.io
          PUBLISH_BRANCH: master
          PUBLISH_DIR: dist
        with:
          emptyCommits: false