#给这个workflow起个名字
name: vuepress-CI
#如何触发,这里是提交到master分支时候触发,
on:
  push:
    branches:
      - master
#具体的操作.
jobs:
  build-deploy:
  	#运行虚拟机环境,Ubuntu是用的最多的.有很多插件,所以咱们也用这个.
    runs-on: ubuntu-latest
    #步骤,uses就是用插件,run就是执行命令.
    steps:
    #checkout插件
      - uses: actions/checkout@v1
      #都这么写.
      - run: npm ci
      #安装咱们要的vuepress组件
      - run: npm install -D vuepress
      #清空之前编译的文件,这个路径是你的docs/.vuepress/config.js里面的dest属性配置的.
      - run: rm -rf dist/
      #编译命令,npm run 是命令, docs:build是在package.json文件中配置的.
      - run: npm run docs:build
      #编译后域名文件会被冲掉,所以手写一个cp进去.
      - run: cp CNAME dist/

      # 发布到 fengshouli.github.io/master
      - name: Deploy
      #这也是个插件,如果想了解更多去他的git看.https://github.com/peaceiris/actions-gh-pages/tree/v2.5.0-rc0
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
        #口令,这个超级坑,下面详细说
          ACTIONS_DEPLOY_KEY: ${{secrets.RSA_KEY}}
          #发布地址
          EXTERNAL_REPOSITORY: fengshouli/fengshouli.github.io
          #发布分支
          PUBLISH_BRANCH: master
          #发布什么文件
          PUBLISH_DIR: dist
        with:
          emptyCommits: false
